# Generated by partner-api-contract/tools/server-sdk/python.mjs. DO NOT EDIT.

from __future__ import annotations
from dataclasses import dataclass
from datetime import date, datetime
from threading import Event
from typing import Literal, cast
from .models import *
from ._runtime import AsyncResource, SyncResource, ResponseMetadata, UNSET, UnsetType

@dataclass(frozen=True, repr=False)
class SyncFoods(SyncResource):
    def search(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        query: str,
        category: FoodCategoryInput | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodSearchResults:
        """searchFoods; shared operation. One HTTP request; no retries."""
        return cast(FoodSearchResults, self._transport.request(
            "searchFoods", {"end_user_id": end_user_id, "query": query, "category": category, "limit": limit}, FoodSearchResults, self._context, timeout, cancel_event,
        ))

    def autocomplete(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        query: str,
        category: AutocompleteFoodCategoryInput | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> AutocompleteFoodsResponse:
        """autocompleteFoods; shared operation. One HTTP request; no retries."""
        return cast(AutocompleteFoodsResponse, self._transport.request(
            "autocompleteFoods", {"end_user_id": end_user_id, "query": query, "category": category, "limit": limit}, AutocompleteFoodsResponse, self._context, timeout, cancel_event,
        ))

    def suggest_alternatives(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        food_id: FoodId,
        diet_restrictions: list[DietRestrictionInput] | UnsetType = UNSET,
        diet_preferences: list[DietPreferenceInput] | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> SuggestFoodAlternativesResponse:
        """suggestFoodAlternatives; shared operation. One HTTP request; no retries."""
        return cast(SuggestFoodAlternativesResponse, self._transport.request(
            "suggestFoodAlternatives", {"end_user_id": end_user_id, "food_id": food_id, "diet_restrictions": diet_restrictions, "diet_preferences": diet_preferences}, SuggestFoodAlternativesResponse, self._context, timeout, cancel_event,
        ))

    def lookup_barcode(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        upc: Barcode,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodSearchResults:
        """lookupFoodByBarcode; shared operation. One HTTP request; no retries."""
        return cast(FoodSearchResults, self._transport.request(
            "lookupFoodByBarcode", {"end_user_id": end_user_id, "upc": upc}, FoodSearchResults, self._context, timeout, cancel_event,
        ))

    def get(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        food_id: FoodId,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodSearchItem:
        """getFood; shared operation. One HTTP request; no retries."""
        return cast(FoodSearchItem, self._transport.request(
            "getFood", {"end_user_id": end_user_id, "food_id": food_id}, FoodSearchItem, self._context, timeout, cancel_event,
        ))

@dataclass(frozen=True, repr=False)
class SyncRestaurants(SyncResource):
    def search(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        radius: float | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        query: str,
        latitude: float,
        longitude: float,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> SearchRestaurantsResponse:
        """searchRestaurants; shared operation. One HTTP request; no retries."""
        return cast(SearchRestaurantsResponse, self._transport.request(
            "searchRestaurants", {"end_user_id": end_user_id, "radius": radius, "limit": limit, "query": query, "latitude": latitude, "longitude": longitude}, SearchRestaurantsResponse, self._context, timeout, cancel_event,
        ))

    def search_menu_items(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        radius: float | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        query: str,
        latitude: float,
        longitude: float,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> SearchRestaurantMenuItemsResponse:
        """searchRestaurantMenuItems; shared operation. One HTTP request; no retries."""
        return cast(SearchRestaurantMenuItemsResponse, self._transport.request(
            "searchRestaurantMenuItems", {"end_user_id": end_user_id, "radius": radius, "limit": limit, "query": query, "latitude": latitude, "longitude": longitude}, SearchRestaurantMenuItemsResponse, self._context, timeout, cancel_event,
        ))

@dataclass(frozen=True, repr=False)
class SyncFoodAnalysis(SyncResource):
    def analyze_photo(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        image: str,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodScan:
        """scanFoodPhoto; shared operation. One HTTP request; no retries."""
        return cast(FoodScan, self._transport.request(
            "scanFoodPhoto", {"end_user_id": end_user_id, "image": image}, FoodScan, self._context, timeout, cancel_event,
        ))

    def analyze_description(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        query: str,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodScan:
        """searchFoodsByNaturalLanguage; shared operation. One HTTP request; no retries."""
        return cast(FoodScan, self._transport.request(
            "searchFoodsByNaturalLanguage", {"end_user_id": end_user_id, "query": query}, FoodScan, self._context, timeout, cancel_event,
        ))

    def correct(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        meal_name: str | UnsetType = UNSET,
        detections: list[FoodDetection | FoodDetectionInput],
        user_input: str,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodScan:
        """correctPhotoScan; shared operation. One HTTP request; no retries."""
        return cast(FoodScan, self._transport.request(
            "correctPhotoScan", {"end_user_id": end_user_id, "meal_name": meal_name, "detections": detections, "user_input": user_input}, FoodScan, self._context, timeout, cancel_event,
        ))

@dataclass(frozen=True, repr=False)
class SyncFoodLogs(SyncResource):
    def create(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        foods: list[FoodLogInputFood | FoodLogInputFoodInput],
        timestamp_utc: str | datetime | UnsetType = UNSET,
        name: str | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodLog:
        """createFoodLog; shared operation. One HTTP request; no retries."""
        return cast(FoodLog, self._transport.request(
            "createFoodLog", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "foods": foods, "timestamp_utc": timestamp_utc, "name": name}, FoodLog, self._context, timeout, cancel_event,
        ))

    def list(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        start: str | date,
        end: str | date,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> ListFoodLogsResponse:
        """listFoodLogs; shared operation. One HTTP request; no retries."""
        return cast(ListFoodLogsResponse, self._transport.request(
            "listFoodLogs", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "start": start, "end": end}, ListFoodLogsResponse, self._context, timeout, cancel_event,
        ))

    def update(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        log_id: FoodLogId,
        foods: list[FoodLogInputFood | FoodLogInputFoodInput] | UnsetType = UNSET,
        timestamp_utc: str | UnsetType = UNSET,
        name: str | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> FoodLog:
        """updateFoodLog; shared operation. One HTTP request; no retries."""
        return cast(FoodLog, self._transport.request(
            "updateFoodLog", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "log_id": log_id, "foods": foods, "timestamp_utc": timestamp_utc, "name": name}, FoodLog, self._context, timeout, cancel_event,
        ))

    def delete(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        log_id: FoodLogId,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> DeleteFoodLogResponse:
        """deleteFoodLog; shared operation. One HTTP request; no retries."""
        return cast(DeleteFoodLogResponse, self._transport.request(
            "deleteFoodLog", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "log_id": log_id}, DeleteFoodLogResponse, self._context, timeout, cancel_event,
        ))

@dataclass(frozen=True, repr=False)
class SyncGlucose(SyncResource):
    def predict(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        user_profile: GlucosePredictionProfile | GlucosePredictionProfileInput,
        foods: list[FoodLogInputFood | FoodLogInputFoodInput],
        start_time: str | datetime,
        cgm_data: list[CgmReading | CgmReadingInput] | UnsetType = UNSET,
        consumed_foods: list[ConsumedHistoricalFood | ConsumedHistoricalFoodInput] | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> GlucosePrediction:
        """predictGlucose; shared operation. One HTTP request; no retries."""
        return cast(GlucosePrediction, self._transport.request(
            "predictGlucose", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "user_profile": user_profile, "foods": foods, "start_time": start_time, "cgm_data": cgm_data, "consumed_foods": consumed_foods}, GlucosePrediction, self._context, timeout, cancel_event,
        ))

@dataclass(frozen=True, repr=False)
class SyncShared(SyncResource):
    @property
    def foods(self) -> SyncFoods:
        return SyncFoods(self._transport, self._context)

    @property
    def restaurants(self) -> SyncRestaurants:
        return SyncRestaurants(self._transport, self._context)

    @property
    def food_analysis(self) -> SyncFoodAnalysis:
        return SyncFoodAnalysis(self._transport, self._context)

    @property
    def food_logs(self) -> SyncFoodLogs:
        return SyncFoodLogs(self._transport, self._context)

    @property
    def glucose(self) -> SyncGlucose:
        return SyncGlucose(self._transport, self._context)

@dataclass(frozen=True, repr=False)
class SyncRoot(SyncShared):
    def mint_client_token(
        self, *,
        end_user_id: str,
        scopes: list[Literal["foods:read", "food_scans:write", "food_logs:read", "food_logs:write", "glucose:read", "restaurants:read"]] | UnsetType = UNSET,
        ttl_seconds: float | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> ClientTokenResponseDto:
        """mintClientToken; server operation. One HTTP request; no retries."""
        return cast(ClientTokenResponseDto, self._transport.request(
            "mintClientToken", {"end_user_id": end_user_id, "scopes": scopes, "ttl_seconds": ttl_seconds}, ClientTokenResponseDto, self._context, timeout, cancel_event,
        ))

    def revoke_client_tokens(
        self, *,
        end_user_id: str,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> ResponseMetadata:
        """revokeClientTokens; server operation. One HTTP request; no retries."""
        return cast(ResponseMetadata, self._transport.request(
            "revokeClientTokens", {"end_user_id": end_user_id}, ResponseMetadata, self._context, timeout, cancel_event,
        ))

    def credits(
        self, *,
        end_user_id: str | UnsetType = UNSET,
        timeout: float | None = None,
        cancel_event: Event | None = None,
    ) -> CreditsResponseDto:
        """credits; server operation. One HTTP request; no retries."""
        return cast(CreditsResponseDto, self._transport.request(
            "credits", {"end_user_id": end_user_id}, CreditsResponseDto, self._context, timeout, cancel_event,
        ))

@dataclass(frozen=True, repr=False)
class AsyncFoods(AsyncResource):
    async def search(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        query: str,
        category: FoodCategoryInput | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> FoodSearchResults:
        """searchFoods; shared operation. One HTTP request; no retries."""
        return cast(FoodSearchResults, await self._transport.request(
            "searchFoods", {"end_user_id": end_user_id, "query": query, "category": category, "limit": limit}, FoodSearchResults, self._context, timeout,
        ))

    async def autocomplete(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        query: str,
        category: AutocompleteFoodCategoryInput | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> AutocompleteFoodsResponse:
        """autocompleteFoods; shared operation. One HTTP request; no retries."""
        return cast(AutocompleteFoodsResponse, await self._transport.request(
            "autocompleteFoods", {"end_user_id": end_user_id, "query": query, "category": category, "limit": limit}, AutocompleteFoodsResponse, self._context, timeout,
        ))

    async def suggest_alternatives(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        food_id: FoodId,
        diet_restrictions: list[DietRestrictionInput] | UnsetType = UNSET,
        diet_preferences: list[DietPreferenceInput] | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> SuggestFoodAlternativesResponse:
        """suggestFoodAlternatives; shared operation. One HTTP request; no retries."""
        return cast(SuggestFoodAlternativesResponse, await self._transport.request(
            "suggestFoodAlternatives", {"end_user_id": end_user_id, "food_id": food_id, "diet_restrictions": diet_restrictions, "diet_preferences": diet_preferences}, SuggestFoodAlternativesResponse, self._context, timeout,
        ))

    async def lookup_barcode(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        upc: Barcode,
        timeout: float | None = None,
    ) -> FoodSearchResults:
        """lookupFoodByBarcode; shared operation. One HTTP request; no retries."""
        return cast(FoodSearchResults, await self._transport.request(
            "lookupFoodByBarcode", {"end_user_id": end_user_id, "upc": upc}, FoodSearchResults, self._context, timeout,
        ))

    async def get(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        food_id: FoodId,
        timeout: float | None = None,
    ) -> FoodSearchItem:
        """getFood; shared operation. One HTTP request; no retries."""
        return cast(FoodSearchItem, await self._transport.request(
            "getFood", {"end_user_id": end_user_id, "food_id": food_id}, FoodSearchItem, self._context, timeout,
        ))

@dataclass(frozen=True, repr=False)
class AsyncRestaurants(AsyncResource):
    async def search(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        radius: float | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        query: str,
        latitude: float,
        longitude: float,
        timeout: float | None = None,
    ) -> SearchRestaurantsResponse:
        """searchRestaurants; shared operation. One HTTP request; no retries."""
        return cast(SearchRestaurantsResponse, await self._transport.request(
            "searchRestaurants", {"end_user_id": end_user_id, "radius": radius, "limit": limit, "query": query, "latitude": latitude, "longitude": longitude}, SearchRestaurantsResponse, self._context, timeout,
        ))

    async def search_menu_items(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        radius: float | UnsetType = UNSET,
        limit: float | UnsetType = UNSET,
        query: str,
        latitude: float,
        longitude: float,
        timeout: float | None = None,
    ) -> SearchRestaurantMenuItemsResponse:
        """searchRestaurantMenuItems; shared operation. One HTTP request; no retries."""
        return cast(SearchRestaurantMenuItemsResponse, await self._transport.request(
            "searchRestaurantMenuItems", {"end_user_id": end_user_id, "radius": radius, "limit": limit, "query": query, "latitude": latitude, "longitude": longitude}, SearchRestaurantMenuItemsResponse, self._context, timeout,
        ))

@dataclass(frozen=True, repr=False)
class AsyncFoodAnalysis(AsyncResource):
    async def analyze_photo(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        image: str,
        timeout: float | None = None,
    ) -> FoodScan:
        """scanFoodPhoto; shared operation. One HTTP request; no retries."""
        return cast(FoodScan, await self._transport.request(
            "scanFoodPhoto", {"end_user_id": end_user_id, "image": image}, FoodScan, self._context, timeout,
        ))

    async def analyze_description(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        query: str,
        timeout: float | None = None,
    ) -> FoodScan:
        """searchFoodsByNaturalLanguage; shared operation. One HTTP request; no retries."""
        return cast(FoodScan, await self._transport.request(
            "searchFoodsByNaturalLanguage", {"end_user_id": end_user_id, "query": query}, FoodScan, self._context, timeout,
        ))

    async def correct(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        meal_name: str | UnsetType = UNSET,
        detections: list[FoodDetection | FoodDetectionInput],
        user_input: str,
        timeout: float | None = None,
    ) -> FoodScan:
        """correctPhotoScan; shared operation. One HTTP request; no retries."""
        return cast(FoodScan, await self._transport.request(
            "correctPhotoScan", {"end_user_id": end_user_id, "meal_name": meal_name, "detections": detections, "user_input": user_input}, FoodScan, self._context, timeout,
        ))

@dataclass(frozen=True, repr=False)
class AsyncFoodLogs(AsyncResource):
    async def create(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        foods: list[FoodLogInputFood | FoodLogInputFoodInput],
        timestamp_utc: str | datetime | UnsetType = UNSET,
        name: str | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> FoodLog:
        """createFoodLog; shared operation. One HTTP request; no retries."""
        return cast(FoodLog, await self._transport.request(
            "createFoodLog", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "foods": foods, "timestamp_utc": timestamp_utc, "name": name}, FoodLog, self._context, timeout,
        ))

    async def list(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        start: str | date,
        end: str | date,
        timeout: float | None = None,
    ) -> ListFoodLogsResponse:
        """listFoodLogs; shared operation. One HTTP request; no retries."""
        return cast(ListFoodLogsResponse, await self._transport.request(
            "listFoodLogs", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "start": start, "end": end}, ListFoodLogsResponse, self._context, timeout,
        ))

    async def update(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        log_id: FoodLogId,
        foods: list[FoodLogInputFood | FoodLogInputFoodInput] | UnsetType = UNSET,
        timestamp_utc: str | UnsetType = UNSET,
        name: str | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> FoodLog:
        """updateFoodLog; shared operation. One HTTP request; no retries."""
        return cast(FoodLog, await self._transport.request(
            "updateFoodLog", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "log_id": log_id, "foods": foods, "timestamp_utc": timestamp_utc, "name": name}, FoodLog, self._context, timeout,
        ))

    async def delete(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        log_id: FoodLogId,
        timeout: float | None = None,
    ) -> DeleteFoodLogResponse:
        """deleteFoodLog; shared operation. One HTTP request; no retries."""
        return cast(DeleteFoodLogResponse, await self._transport.request(
            "deleteFoodLog", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "log_id": log_id}, DeleteFoodLogResponse, self._context, timeout,
        ))

@dataclass(frozen=True, repr=False)
class AsyncGlucose(AsyncResource):
    async def predict(
        self, *,
        end_user_id: PartnerUserId | UnsetType = UNSET,
        end_user_timezone: str | UnsetType = UNSET,
        user_profile: GlucosePredictionProfile | GlucosePredictionProfileInput,
        foods: list[FoodLogInputFood | FoodLogInputFoodInput],
        start_time: str | datetime,
        cgm_data: list[CgmReading | CgmReadingInput] | UnsetType = UNSET,
        consumed_foods: list[ConsumedHistoricalFood | ConsumedHistoricalFoodInput] | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> GlucosePrediction:
        """predictGlucose; shared operation. One HTTP request; no retries."""
        return cast(GlucosePrediction, await self._transport.request(
            "predictGlucose", {"end_user_id": end_user_id, "end_user_timezone": end_user_timezone, "user_profile": user_profile, "foods": foods, "start_time": start_time, "cgm_data": cgm_data, "consumed_foods": consumed_foods}, GlucosePrediction, self._context, timeout,
        ))

@dataclass(frozen=True, repr=False)
class AsyncShared(AsyncResource):
    @property
    def foods(self) -> AsyncFoods:
        return AsyncFoods(self._transport, self._context)

    @property
    def restaurants(self) -> AsyncRestaurants:
        return AsyncRestaurants(self._transport, self._context)

    @property
    def food_analysis(self) -> AsyncFoodAnalysis:
        return AsyncFoodAnalysis(self._transport, self._context)

    @property
    def food_logs(self) -> AsyncFoodLogs:
        return AsyncFoodLogs(self._transport, self._context)

    @property
    def glucose(self) -> AsyncGlucose:
        return AsyncGlucose(self._transport, self._context)

@dataclass(frozen=True, repr=False)
class AsyncRoot(AsyncShared):
    async def mint_client_token(
        self, *,
        end_user_id: str,
        scopes: list[Literal["foods:read", "food_scans:write", "food_logs:read", "food_logs:write", "glucose:read", "restaurants:read"]] | UnsetType = UNSET,
        ttl_seconds: float | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> ClientTokenResponseDto:
        """mintClientToken; server operation. One HTTP request; no retries."""
        return cast(ClientTokenResponseDto, await self._transport.request(
            "mintClientToken", {"end_user_id": end_user_id, "scopes": scopes, "ttl_seconds": ttl_seconds}, ClientTokenResponseDto, self._context, timeout,
        ))

    async def revoke_client_tokens(
        self, *,
        end_user_id: str,
        timeout: float | None = None,
    ) -> ResponseMetadata:
        """revokeClientTokens; server operation. One HTTP request; no retries."""
        return cast(ResponseMetadata, await self._transport.request(
            "revokeClientTokens", {"end_user_id": end_user_id}, ResponseMetadata, self._context, timeout,
        ))

    async def credits(
        self, *,
        end_user_id: str | UnsetType = UNSET,
        timeout: float | None = None,
    ) -> CreditsResponseDto:
        """credits; server operation. One HTTP request; no retries."""
        return cast(CreditsResponseDto, await self._transport.request(
            "credits", {"end_user_id": end_user_id}, CreditsResponseDto, self._context, timeout,
        ))
