# Generated by partner-api-contract/tools/server-sdk/python.mjs. DO NOT EDIT.

from __future__ import annotations
from datetime import datetime
from typing import Literal
from typing_extensions import Required, TypedDict
from pydantic import Field
from ._runtime import APIModel

ActivityLevel = str
ActivityLevelInput = Literal["sedentary", "lightly_active", "moderately_active", "very_active"]
AutocompleteFoodCategory = str
AutocompleteFoodCategoryInput = Literal["general", "branded"]
Barcode = str
ConfidenceScore = str
ConfidenceScoreInput = Literal["high", "medium", "low"]
DietPreference = str
DietPreferenceInput = Literal["vegetarian", "vegan", "keto", "paleo", "pescatarian", "low_carbohydrate", "high_protein", "kosher", "halal"]
DietRestriction = str
DietRestrictionInput = Literal["gluten", "lactose", "yeast", "tree_nuts", "peanuts", "dairy", "eggs", "sulfites", "soy", "wheat", "shellfish", "fish", "mushrooms", "sesame", "msg", "caffeine", "fodmaps"]
FoodCategory = str
FoodCategoryInput = Literal["general", "branded", "recipe"]
FoodId = int
FoodLogId = str
GlucoseImpact = str
GlucoseImpactInput = Literal["low", "medium", "high"]
HeightUnit = str
HeightUnitInput = Literal["in", "cm"]
MedicalCondition = str
MedicalConditionInput = Literal["type_2_diabetes", "prediabetes"]
PartnerUserId = str
RestaurantMenuItemId = str
ServingId = int
Sex = str
SexInput = Literal["male", "female"]
WeightUnit = str
WeightUnitInput = Literal["lb", "kg"]

class AlternativeFood(APIModel):
    id: FoodId | None = Field(None, alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(None, alias="brand_name", repr=False)
    nutrients: CompleteScanNutritionFacts = Field(..., alias="nutrients", repr=False)
    servings: list[AlternativeServing] | None = Field(None, alias="servings", repr=False)

class AlternativeFoodInput(TypedDict, total=False):
    id: FoodId
    name: Required[str]
    brand_name: str
    nutrients: Required[CompleteScanNutritionFacts | CompleteScanNutritionFactsInput]
    servings: list[AlternativeServing | AlternativeServingInput]

class AlternativeServing(APIModel):
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float | None = Field(None, alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)

class AlternativeServingInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: float
    unit: Required[str]

class ApiErrorDto(APIModel):
    message: str = Field(..., alias="message", repr=False)
    code: str = Field(..., alias="code", repr=False)
    docs_url: str = Field(..., alias="docs_url", repr=False)

class ApiErrorDtoInput(TypedDict, total=False):
    message: Required[str]
    code: Required[str]
    docs_url: Required[str]

class AutocompleteFoodsResponse(APIModel):
    items: list[FoodSuggestion] = Field(..., alias="items", repr=False)

class AutocompleteFoodsResponseInput(TypedDict, total=False):
    items: Required[list[FoodSuggestion | FoodSuggestionInput]]

class CgmReading(APIModel):
    timestamp: str = Field(..., alias="timestamp", repr=False)
    value: float = Field(..., alias="value", repr=False)

class CgmReadingInput(TypedDict, total=False):
    timestamp: Required[str | datetime]
    value: Required[float]

class ClientTokenResponseDto(APIModel):
    token: str = Field(..., alias="token", repr=False)
    expires_in: float = Field(..., alias="expires_in", repr=False)
    expires_at: str = Field(..., alias="expires_at", repr=False)
    end_user_id: str = Field(..., alias="end_user_id", repr=False)
    scopes: list[str] = Field(..., alias="scopes", repr=False)

class ClientTokenResponseDtoInput(TypedDict, total=False):
    token: Required[str]
    expires_in: Required[float]
    expires_at: Required[str]
    end_user_id: Required[str]
    scopes: Required[list[Literal["foods:read", "food_scans:write", "food_logs:read", "food_logs:write", "glucose:read", "restaurants:read"]]]

class CompleteScanNutritionFacts(APIModel):
    calories: NutrientAmount | None = Field(None, alias="calories", repr=False)
    protein: NutrientAmount | None = Field(None, alias="protein", repr=False)
    carbohydrates: NutrientAmount | None = Field(None, alias="carbohydrates", repr=False)
    net_carbohydrates: NutrientAmount | None = Field(None, alias="net_carbohydrates", repr=False)
    total_fat: NutrientAmount | None = Field(None, alias="total_fat", repr=False)
    saturated_fat: NutrientAmount | None = Field(None, alias="saturated_fat", repr=False)
    fiber: NutrientAmount | None = Field(None, alias="fiber", repr=False)
    total_sugars: NutrientAmount | None = Field(None, alias="total_sugars", repr=False)
    added_sugars: NutrientAmount | None = Field(None, alias="added_sugars", repr=False)
    sodium: NutrientAmount | None = Field(None, alias="sodium", repr=False)

class CompleteScanNutritionFactsInput(TypedDict, total=False):
    calories: NutrientAmount | NutrientAmountInput
    protein: NutrientAmount | NutrientAmountInput
    carbohydrates: NutrientAmount | NutrientAmountInput
    net_carbohydrates: NutrientAmount | NutrientAmountInput
    total_fat: NutrientAmount | NutrientAmountInput
    saturated_fat: NutrientAmount | NutrientAmountInput
    fiber: NutrientAmount | NutrientAmountInput
    total_sugars: NutrientAmount | NutrientAmountInput
    added_sugars: NutrientAmount | NutrientAmountInput
    sodium: NutrientAmount | NutrientAmountInput

class ConsumedHistoricalFood(APIModel):
    timestamp: str = Field(..., alias="timestamp", repr=False)
    id: FoodId = Field(..., alias="id", repr=False)
    serving: FoodLogInputServing = Field(..., alias="serving", repr=False)

class ConsumedHistoricalFoodInput(TypedDict, total=False):
    timestamp: Required[str | datetime]
    id: Required[FoodId]
    serving: Required[FoodLogInputServing | FoodLogInputServingInput]

class CorrectPhotoScanBody(APIModel):
    meal_name: str | None = Field(None, alias="meal_name", repr=False)
    detections: list[FoodDetection] = Field(..., alias="detections", repr=False)
    user_input: str = Field(..., alias="user_input", repr=False)

class CorrectPhotoScanBodyInput(TypedDict, total=False):
    meal_name: str
    detections: Required[list[FoodDetection | FoodDetectionInput]]
    user_input: Required[str]

class CreateClientTokenDto(APIModel):
    end_user_id: str = Field(..., alias="end_user_id", repr=False)
    scopes: list[str] | None = Field(None, alias="scopes", repr=False)
    ttl_seconds: float | None = Field(None, alias="ttl_seconds", repr=False)

class CreateClientTokenDtoInput(TypedDict, total=False):
    end_user_id: Required[str]
    scopes: list[Literal["foods:read", "food_scans:write", "food_logs:read", "food_logs:write", "glucose:read", "restaurants:read"]]
    ttl_seconds: float

class CreateFoodLogBody(APIModel):
    foods: list[FoodLogInputFood] = Field(..., alias="foods", repr=False)
    timestamp_utc: str | None = Field(None, alias="timestamp_utc", repr=False)
    name: str | None = Field(None, alias="name", repr=False)

class CreateFoodLogBodyInput(TypedDict, total=False):
    foods: Required[list[FoodLogInputFood | FoodLogInputFoodInput]]
    timestamp_utc: str | datetime
    name: str

class CreditsResponseDto(APIModel):
    plan: str = Field(..., alias="plan", repr=False)
    period_start: str = Field(..., alias="period_start", repr=False)
    period_end: str = Field(..., alias="period_end", repr=False)
    resets_at: str = Field(..., alias="resets_at", repr=False)
    included_credits: float | None = Field(None, alias="included_credits", repr=False)
    used_credits: float = Field(..., alias="used_credits", repr=False)
    remaining_credits: float | None = Field(None, alias="remaining_credits", repr=False)

class CreditsResponseDtoInput(TypedDict, total=False):
    plan: Required[str]
    period_start: Required[str]
    period_end: Required[str]
    resets_at: Required[str]
    included_credits: float
    used_credits: Required[float]
    remaining_credits: float

class DeleteFoodLogResponse(APIModel):
    status: str = Field(..., alias="status", repr=False)

class DeleteFoodLogResponseInput(TypedDict, total=False):
    status: Required[str]

class DetectedFood(APIModel):
    id: FoodId | None = Field(None, alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(None, alias="brand_name", repr=False)
    nutrients: CompleteScanNutritionFacts = Field(..., alias="nutrients", repr=False)
    servings: list[DetectedServing] = Field(..., alias="servings", repr=False)

class DetectedFoodInput(TypedDict, total=False):
    id: FoodId
    name: Required[str]
    brand_name: str
    nutrients: Required[CompleteScanNutritionFacts | CompleteScanNutritionFactsInput]
    servings: Required[list[DetectedServing | DetectedServingInput]]

class DetectedServing(APIModel):
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float | None = Field(None, alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)
    selected_quantity: float | None = Field(None, alias="selected_quantity", repr=False)

class DetectedServingInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: float
    unit: Required[str]
    selected_quantity: float

class ErrorResponse(APIModel):
    message: str = Field(..., alias="message", repr=False)
    code: str = Field(..., alias="code", repr=False)
    docs_url: str = Field(..., alias="docs_url", repr=False)

class ErrorResponseInput(TypedDict, total=False):
    message: Required[str]
    code: Required[str]
    docs_url: Required[str]

class FoodAlternative(APIModel):
    food: AlternativeFood = Field(..., alias="food", repr=False)

class FoodAlternativeInput(TypedDict, total=False):
    food: Required[AlternativeFood | AlternativeFoodInput]

class FoodDetection(APIModel):
    confidence_score: ConfidenceScore | None = Field(None, alias="confidence_score", repr=False)
    food: DetectedFood = Field(..., alias="food", repr=False)

class FoodDetectionInput(TypedDict, total=False):
    confidence_score: ConfidenceScoreInput
    food: Required[DetectedFood | DetectedFoodInput]

class FoodLog(APIModel):
    id: FoodLogId = Field(..., alias="id", repr=False)
    foods: list[LoggedFood] = Field(..., alias="foods", repr=False)
    timestamp_utc: str = Field(..., alias="timestamp_utc", repr=False)
    name: str | None = Field(None, alias="name", repr=False)

class FoodLogInput(TypedDict, total=False):
    id: Required[FoodLogId]
    foods: Required[list[LoggedFood | LoggedFoodInput]]
    timestamp_utc: Required[str]
    name: str | None

class FoodLogInputFood(APIModel):
    id: FoodId = Field(..., alias="id", repr=False)
    serving: FoodLogInputServing = Field(..., alias="serving", repr=False)

class FoodLogInputFoodInput(TypedDict, total=False):
    id: Required[FoodId]
    serving: Required[FoodLogInputServing | FoodLogInputServingInput]

class FoodLogInputServing(APIModel):
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float = Field(..., alias="quantity", repr=False)

class FoodLogInputServingInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: Required[float]

class FoodScan(APIModel):
    meal_name: str | None = Field(None, alias="meal_name", repr=False)
    total_nutrients: CompleteScanNutritionFacts | None = Field(None, alias="total_nutrients", repr=False)
    detections: list[FoodDetection] = Field(..., alias="detections", repr=False)

class FoodScanInput(TypedDict, total=False):
    meal_name: str
    total_nutrients: CompleteScanNutritionFacts | CompleteScanNutritionFactsInput
    detections: Required[list[FoodDetection | FoodDetectionInput]]

class FoodSearchItem(APIModel):
    id: FoodId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(None, alias="brand_name", repr=False)
    nutrients: NutritionFacts = Field(..., alias="nutrients", repr=False)
    glycemic_index: float | None = Field(None, alias="glycemic_index", repr=False)
    glycemic_load: float | None = Field(None, alias="glycemic_load", repr=False)
    image_url: str | None = Field(None, alias="image_url", repr=False)
    upc: str | None = Field(None, alias="upc", repr=False)
    servings: list[ServingOption] = Field(..., alias="servings", repr=False)

class FoodSearchItemInput(TypedDict, total=False):
    id: Required[FoodId]
    name: Required[str]
    brand_name: str
    nutrients: Required[NutritionFacts | NutritionFactsInput]
    glycemic_index: float
    glycemic_load: float
    image_url: str
    upc: str
    servings: Required[list[ServingOption | ServingOptionInput]]

class FoodSearchResults(APIModel):
    total_count: float = Field(..., alias="total_count", repr=False)
    items: list[FoodSearchItem] = Field(..., alias="items", repr=False)

class FoodSearchResultsInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[list[FoodSearchItem | FoodSearchItemInput]]

class FoodSuggestion(APIModel):
    id: FoodId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(None, alias="brand_name", repr=False)
    image_url: str | None = Field(None, alias="image_url", repr=False)
    nutrients: NutritionFacts | None = Field(None, alias="nutrients", repr=False)

class FoodSuggestionInput(TypedDict, total=False):
    id: Required[FoodId]
    name: Required[str]
    brand_name: str
    image_url: str
    nutrients: NutritionFacts | NutritionFactsInput

class GlucoseChart(APIModel):
    min: float = Field(..., alias="min", repr=False)
    max: float = Field(..., alias="max", repr=False)

class GlucoseChartInput(TypedDict, total=False):
    min: Required[float]
    max: Required[float]

class GlucosePrediction(APIModel):
    prediction: list[GlucosePredictionPoint] = Field(..., alias="prediction", repr=False)
    impact: GlucoseImpact = Field(..., alias="impact_score", repr=False)
    chart: GlucoseChart = Field(..., alias="chart", repr=False)

class GlucosePredictionInput(TypedDict, total=False):
    prediction: Required[list[GlucosePredictionPoint | GlucosePredictionPointInput]]
    impact_score: Required[GlucoseImpactInput]
    chart: Required[GlucoseChart | GlucoseChartInput]

class GlucosePredictionPoint(APIModel):
    minutes: float = Field(..., alias="minutes", repr=False)
    value: float = Field(..., alias="value", repr=False)

class GlucosePredictionPointInput(TypedDict, total=False):
    minutes: Required[float]
    value: Required[float]

class GlucosePredictionProfile(APIModel):
    age: float = Field(..., alias="age", repr=False)
    sex: Sex = Field(..., alias="sex", repr=False)
    height: Height = Field(..., alias="height", repr=False)
    weight: Weight = Field(..., alias="weight", repr=False)
    activity_level: ActivityLevel | None = Field(None, alias="activity_level", repr=False)
    health_conditions: list[MedicalCondition] | None = Field(None, alias="health_conditions", repr=False)

class GlucosePredictionProfileInput(TypedDict, total=False):
    age: Required[float]
    sex: Required[SexInput]
    height: Required[Height | HeightInput]
    weight: Required[Weight | WeightInput]
    activity_level: ActivityLevelInput
    health_conditions: list[MedicalConditionInput]

class Height(APIModel):
    value: float = Field(..., alias="value", repr=False)
    unit: HeightUnit = Field(..., alias="unit", repr=False)

class HeightInput(TypedDict, total=False):
    value: Required[float]
    unit: Required[HeightUnitInput]

class ListFoodLogsResponse(APIModel):
    total_count: float = Field(..., alias="total_count", repr=False)
    items: list[FoodLog] = Field(..., alias="items", repr=False)

class ListFoodLogsResponseInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[list[FoodLog | FoodLogInput]]

class LoggedFood(APIModel):
    id: FoodId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(None, alias="brand_name", repr=False)
    image_url: str | None = Field(None, alias="image_url", repr=False)
    glycemic_index: float | None = Field(None, alias="glycemic_index", repr=False)
    glycemic_load: float | None = Field(None, alias="glycemic_load", repr=False)
    nutrients: NutritionFacts = Field(..., alias="nutrients", repr=False)
    consumed_serving: FoodLogInputServing = Field(..., alias="consumed_serving", repr=False)
    serving_details: ServingDetails = Field(..., alias="serving_details", repr=False)

class LoggedFoodInput(TypedDict, total=False):
    id: Required[FoodId]
    name: Required[str]
    brand_name: str | None
    image_url: str | None
    glycemic_index: float | None
    glycemic_load: float | None
    nutrients: Required[NutritionFacts | NutritionFactsInput]
    consumed_serving: Required[FoodLogInputServing | FoodLogInputServingInput]
    serving_details: Required[ServingDetails | ServingDetailsInput]

class NutrientAmount(APIModel):
    value: float = Field(..., alias="value", repr=False)
    unit: str = Field(..., alias="unit", repr=False)

class NutrientAmountInput(TypedDict, total=False):
    value: Required[float]
    unit: Required[str]

class NutritionFacts(APIModel):
    calories: NutrientAmount | None = Field(None, alias="calories", repr=False)
    protein: NutrientAmount | None = Field(None, alias="protein", repr=False)
    carbohydrates: NutrientAmount | None = Field(None, alias="carbohydrates", repr=False)
    net_carbohydrates: NutrientAmount | None = Field(None, alias="net_carbohydrates", repr=False)
    total_fat: NutrientAmount | None = Field(None, alias="total_fat", repr=False)
    trans_fat: NutrientAmount | None = Field(None, alias="trans_fat", repr=False)
    saturated_fat: NutrientAmount | None = Field(None, alias="saturated_fat", repr=False)
    fiber: NutrientAmount | None = Field(None, alias="fiber", repr=False)
    total_sugars: NutrientAmount | None = Field(None, alias="total_sugars", repr=False)
    added_sugars: NutrientAmount | None = Field(None, alias="added_sugars", repr=False)
    cholesterol: NutrientAmount | None = Field(None, alias="cholesterol", repr=False)
    calcium: NutrientAmount | None = Field(None, alias="calcium", repr=False)
    iron: NutrientAmount | None = Field(None, alias="iron", repr=False)
    potassium: NutrientAmount | None = Field(None, alias="potassium", repr=False)
    sodium: NutrientAmount | None = Field(None, alias="sodium", repr=False)
    vitamin_d: NutrientAmount | None = Field(None, alias="vitamin_d", repr=False)

class NutritionFactsInput(TypedDict, total=False):
    calories: NutrientAmount | NutrientAmountInput
    protein: NutrientAmount | NutrientAmountInput
    carbohydrates: NutrientAmount | NutrientAmountInput
    net_carbohydrates: NutrientAmount | NutrientAmountInput
    total_fat: NutrientAmount | NutrientAmountInput
    trans_fat: NutrientAmount | NutrientAmountInput
    saturated_fat: NutrientAmount | NutrientAmountInput
    fiber: NutrientAmount | NutrientAmountInput
    total_sugars: NutrientAmount | NutrientAmountInput
    added_sugars: NutrientAmount | NutrientAmountInput
    cholesterol: NutrientAmount | NutrientAmountInput
    calcium: NutrientAmount | NutrientAmountInput
    iron: NutrientAmount | NutrientAmountInput
    potassium: NutrientAmount | NutrientAmountInput
    sodium: NutrientAmount | NutrientAmountInput
    vitamin_d: NutrientAmount | NutrientAmountInput

class PredictGlucoseBody(APIModel):
    user_profile: GlucosePredictionProfile = Field(..., alias="user_profile", repr=False)
    foods: list[FoodLogInputFood] = Field(..., alias="foods", repr=False)
    start_time: str = Field(..., alias="start_time", repr=False)
    cgm_data: list[CgmReading] | None = Field(None, alias="cgm_data", repr=False)
    consumed_foods: list[ConsumedHistoricalFood] | None = Field(None, alias="consumed_foods", repr=False)

class PredictGlucoseBodyInput(TypedDict, total=False):
    user_profile: Required[GlucosePredictionProfile | GlucosePredictionProfileInput]
    foods: Required[list[FoodLogInputFood | FoodLogInputFoodInput]]
    start_time: Required[str | datetime]
    cgm_data: list[CgmReading | CgmReadingInput]
    consumed_foods: list[ConsumedHistoricalFood | ConsumedHistoricalFoodInput]

class Restaurant(APIModel):
    type_: str = Field(..., alias="type", repr=False)
    id: str = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    is_chain: bool | None = Field(None, alias="is_chain", repr=False)
    distance: float | None = Field(None, alias="distance", repr=False)
    city: str | None = Field(None, alias="city", repr=False)
    address1: str | None = Field(None, alias="address1", repr=False)
    address2: str | None = Field(None, alias="address2", repr=False)

class RestaurantInput(TypedDict, total=False):
    type_: Required[Literal["restaurant", "menu_item"]]
    id: Required[str]
    name: Required[str]
    is_chain: bool
    distance: float
    city: str
    address1: str
    address2: str

class RestaurantMenuItem(APIModel):
    type_: str = Field(..., alias="type", repr=False)
    id: RestaurantMenuItemId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    restaurant_name: str = Field(..., alias="restaurant_name", repr=False)
    is_chain: bool | None = Field(None, alias="is_chain", repr=False)
    nutrients: NutritionFacts | None = Field(None, alias="nutrients", repr=False)
    glycemic_index: float | None = Field(None, alias="glycemic_index", repr=False)
    glycemic_load: float | None = Field(None, alias="glycemic_load", repr=False)
    image_url: str | None = Field(None, alias="image_url", repr=False)
    distance: float | None = Field(None, alias="distance", repr=False)
    servings: list[ServingOption] = Field(..., alias="servings", repr=False)

class RestaurantMenuItemInput(TypedDict, total=False):
    type_: Required[str]
    id: Required[RestaurantMenuItemId]
    name: Required[str]
    restaurant_name: Required[str]
    is_chain: bool
    nutrients: NutritionFacts | NutritionFactsInput
    glycemic_index: float
    glycemic_load: float
    image_url: str
    distance: float
    servings: Required[list[ServingOption | ServingOptionInput]]

class ScanFoodPhotoBody(APIModel):
    image: str = Field(..., alias="image", repr=False)

class ScanFoodPhotoBodyInput(TypedDict, total=False):
    image: Required[str]

class SearchFoodsByNaturalLanguageBody(APIModel):
    text: str = Field(..., alias="text", repr=False)

class SearchFoodsByNaturalLanguageBodyInput(TypedDict, total=False):
    text: Required[str]

class SearchRestaurantMenuItemsResponse(APIModel):
    total_count: float = Field(..., alias="total_count", repr=False)
    items: list[RestaurantMenuItem] = Field(..., alias="items", repr=False)

class SearchRestaurantMenuItemsResponseInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[list[RestaurantMenuItem | RestaurantMenuItemInput]]

class SearchRestaurantsResponse(APIModel):
    total_count: float = Field(..., alias="total_count", repr=False)
    items: list[Restaurant] = Field(..., alias="items", repr=False)

class SearchRestaurantsResponseInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[list[Restaurant | RestaurantInput]]

class ServingDetails(APIModel):
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float = Field(..., alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)
    weight_grams: float | None = Field(None, alias="weight_grams", repr=False)

class ServingDetailsInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: Required[float]
    unit: Required[str]
    weight_grams: float | None

class ServingOption(APIModel):
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float = Field(..., alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)
    scaling_factor: float = Field(..., alias="scaling_factor", repr=False)
    weight_grams: float | None = Field(..., alias="weight_grams", repr=False)
    is_primary: bool = Field(..., alias="is_primary", repr=False)

class ServingOptionInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: Required[float]
    unit: Required[str]
    scaling_factor: Required[float]
    weight_grams: Required[float | None]
    is_primary: Required[bool]

class SuggestFoodAlternativesBody(APIModel):
    diet_restrictions: list[DietRestriction] | None = Field(None, alias="diet_restrictions", repr=False)
    diet_preferences: list[DietPreference] | None = Field(None, alias="diet_preferences", repr=False)

class SuggestFoodAlternativesBodyInput(TypedDict, total=False):
    diet_restrictions: list[DietRestrictionInput]
    diet_preferences: list[DietPreferenceInput]

class SuggestFoodAlternativesResponse(APIModel):
    alternatives: list[FoodAlternative] = Field(..., alias="alternatives", repr=False)

class SuggestFoodAlternativesResponseInput(TypedDict, total=False):
    alternatives: Required[list[FoodAlternative | FoodAlternativeInput]]

class UpdateFoodLogBody(APIModel):
    foods: list[FoodLogInputFood] | None = Field(None, alias="foods", repr=False)
    timestamp_utc: str | None = Field(None, alias="timestamp_utc", repr=False)
    name: str | None = Field(None, alias="name", repr=False)

class UpdateFoodLogBodyInput(TypedDict, total=False):
    foods: list[FoodLogInputFood | FoodLogInputFoodInput]
    timestamp_utc: str
    name: str

class Weight(APIModel):
    value: float = Field(..., alias="value", repr=False)
    unit: WeightUnit = Field(..., alias="unit", repr=False)

class WeightInput(TypedDict, total=False):
    value: Required[float]
    unit: Required[WeightUnitInput]

# Resolve forward references after every schema has been declared.
AlternativeFood.model_rebuild()
AlternativeServing.model_rebuild()
ApiErrorDto.model_rebuild()
AutocompleteFoodsResponse.model_rebuild()
CgmReading.model_rebuild()
ClientTokenResponseDto.model_rebuild()
CompleteScanNutritionFacts.model_rebuild()
ConsumedHistoricalFood.model_rebuild()
CorrectPhotoScanBody.model_rebuild()
CreateClientTokenDto.model_rebuild()
CreateFoodLogBody.model_rebuild()
CreditsResponseDto.model_rebuild()
DeleteFoodLogResponse.model_rebuild()
DetectedFood.model_rebuild()
DetectedServing.model_rebuild()
ErrorResponse.model_rebuild()
FoodAlternative.model_rebuild()
FoodDetection.model_rebuild()
FoodLog.model_rebuild()
FoodLogInputFood.model_rebuild()
FoodLogInputServing.model_rebuild()
FoodScan.model_rebuild()
FoodSearchItem.model_rebuild()
FoodSearchResults.model_rebuild()
FoodSuggestion.model_rebuild()
GlucoseChart.model_rebuild()
GlucosePrediction.model_rebuild()
GlucosePredictionPoint.model_rebuild()
GlucosePredictionProfile.model_rebuild()
Height.model_rebuild()
ListFoodLogsResponse.model_rebuild()
LoggedFood.model_rebuild()
NutrientAmount.model_rebuild()
NutritionFacts.model_rebuild()
PredictGlucoseBody.model_rebuild()
Restaurant.model_rebuild()
RestaurantMenuItem.model_rebuild()
ScanFoodPhotoBody.model_rebuild()
SearchFoodsByNaturalLanguageBody.model_rebuild()
SearchRestaurantMenuItemsResponse.model_rebuild()
SearchRestaurantsResponse.model_rebuild()
ServingDetails.model_rebuild()
ServingOption.model_rebuild()
SuggestFoodAlternativesBody.model_rebuild()
SuggestFoodAlternativesResponse.model_rebuild()
UpdateFoodLogBody.model_rebuild()
Weight.model_rebuild()
