# Generated by partner-api-contract/tools/server-sdk/python.mjs. DO NOT EDIT.

from __future__ import annotations
from collections.abc import Sequence
from datetime import datetime
from typing import Literal
from typing_extensions import Required, TypedDict
from pydantic import Field
from ._runtime import APIModel, parse_api_datetime

ActivityLevel = str
ActivityLevelInput = Literal["sedentary", "lightly_active", "moderately_active", "very_active"]
AutocompleteFoodCategory = str
AutocompleteFoodCategoryInput = Literal["general", "branded"]
Barcode = str
ConfidenceScore = str
ConfidenceScoreInput = Literal["high", "medium", "low"]
DietPreference = str
DietPreferenceInput = Literal["vegetarian", "vegan", "keto", "paleo", "pescatarian", "low_carbohydrate", "high_protein", "kosher", "halal"]
DietRestriction = str
DietRestrictionInput = Literal["gluten", "lactose", "yeast", "tree_nuts", "peanuts", "dairy", "eggs", "sulfites", "soy", "wheat", "shellfish", "fish", "mushrooms", "sesame", "msg", "caffeine", "fodmaps"]
FoodCategory = str
FoodCategoryInput = Literal["general", "branded", "recipe"]
FoodId = int
FoodLogId = str
GlucoseImpact = str
GlucoseImpactInput = Literal["low", "medium", "high"]
HeightUnit = str
HeightUnitInput = Literal["in", "cm"]
MedicalCondition = str
MedicalConditionInput = Literal["type_2_diabetes", "prediabetes"]
PartnerUserId = str
RestaurantMenuItemId = str
ServingId = int
Sex = str
SexInput = Literal["male", "female"]
WeightUnit = str
WeightUnitInput = Literal["lb", "kg"]

class AlternativeFood(APIModel):
    "AlternativeFood: typed API data. Unknown response fields are preserved."
    id: FoodId | None = Field(default=None, alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(default=None, alias="brand_name", repr=False, description="Empty for generic (non-branded) foods.")
    nutrients: CompleteScanNutritionFacts = Field(..., alias="nutrients", repr=False)
    servings: list[AlternativeServing] | None = Field(default=None, alias="servings", repr=False)

class AlternativeFoodInput(TypedDict, total=False):
    id: FoodId
    name: Required[str]
    brand_name: str
    nutrients: Required[CompleteScanNutritionFacts | CompleteScanNutritionFactsInput]
    servings: Sequence[AlternativeServing | AlternativeServingInput]

class AlternativeServing(APIModel):
    "AlternativeServing: typed API data. Unknown response fields are preserved."
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float | None = Field(default=None, alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)

class AlternativeServingInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: float
    unit: Required[str]

class ApiErrorDto(APIModel):
    "ApiErrorDto: typed API data. Unknown response fields are preserved."
    message: str = Field(..., alias="message", repr=False, description="A developer-facing explanation of what went wrong and how to fix it.")
    code: str = Field(..., alias="code", repr=False, description="A stable machine-readable identifier for the class of failure — build retry logic on this, never on message wording. Current values: invalid_request, unauthorized, forbidden, not_found, not_implemented, payload_too_large, rate_limited, internal_error, upstream_error, service_unavailable, upstream_timeout. Only rate_limited, internal_error, upstream_error, service_unavailable, and upstream_timeout are safe to retry (with backoff) — not_implemented is permanent until the feature ships. New codes may be added over time; treat an unknown code according to its HTTP status class.")
    docs_url: str = Field(..., alias="docs_url", repr=False, description="Link to the developer documentation.")

class ApiErrorDtoInput(TypedDict, total=False):
    message: Required[str]
    code: Required[str]
    docs_url: Required[str]

class AutocompleteFoodsResponse(APIModel):
    "AutocompleteFoodsResponse: typed API data. Unknown response fields are preserved."
    items: list[FoodSuggestion] = Field(..., alias="items", repr=False, description="Ranked suggestions, generic foods before branded. Empty when nothing matches.")

class AutocompleteFoodsResponseInput(TypedDict, total=False):
    items: Required[Sequence[FoodSuggestion | FoodSuggestionInput]]

class CgmReading(APIModel):
    "CgmReading: typed API data. Unknown response fields are preserved."
    timestamp: datetime = Field(..., alias="timestamp", repr=False)
    value: float = Field(..., alias="value", repr=False, description="mg/dL. At most one reading per 15-minute window.")

class CgmReadingInput(TypedDict, total=False):
    timestamp: Required[str | datetime]
    value: Required[float]

class ClientTokenResponseDto(APIModel):
    "ClientTokenResponseDto: typed API data. Unknown response fields are preserved."
    token: str = Field(..., alias="token", repr=False, description="The credential itself. Shown exactly once — it is stored only as a hash and can never be retrieved again.")
    expires_in: float = Field(..., alias="expires_in", repr=False, description="Seconds until the token expires, counted from the moment this response was produced. Compute expiry from this rather than from `expires_at` — a device clock that is wrong makes an absolute timestamp wrong with it.")
    expires_at: str = Field(..., alias="expires_at", repr=False, description="The same expiry as an absolute UTC instant, for logs and humans.")
    end_user_id: str = Field(..., alias="end_user_id", repr=False, description="The end user this token is bound to, echoed back so a caller can assert it minted what it meant to.")
    scopes: list[str] = Field(..., alias="scopes", repr=False, description="What this token may do — the scopes granted, whether requested explicitly or defaulted.")

    @property
    def expires_at_datetime(self) -> datetime | None:
        """Aware datetime when parseable; None for opaque/naive timestamps. Raw field is unchanged."""
        return parse_api_datetime(self.expires_at)

class ClientTokenResponseDtoInput(TypedDict, total=False):
    token: Required[str]
    expires_in: Required[float]
    expires_at: Required[str]
    end_user_id: Required[str]
    scopes: Required[Sequence[Literal["foods:read", "food_scans:write", "food_logs:read", "food_logs:write", "glucose:read", "restaurants:read"]]]

class CompleteScanNutritionFacts(APIModel):
    "Nutrients reported by analysis and alternatives. Each key may be omitted when not supplied. An absent key is not a measured zero. Present amounts retain their value and unit."
    calories: NutrientAmount | None = Field(default=None, alias="calories", repr=False)
    protein: NutrientAmount | None = Field(default=None, alias="protein", repr=False)
    carbohydrates: NutrientAmount | None = Field(default=None, alias="carbohydrates", repr=False)
    net_carbohydrates: NutrientAmount | None = Field(default=None, alias="net_carbohydrates", repr=False)
    total_fat: NutrientAmount | None = Field(default=None, alias="total_fat", repr=False)
    saturated_fat: NutrientAmount | None = Field(default=None, alias="saturated_fat", repr=False)
    fiber: NutrientAmount | None = Field(default=None, alias="fiber", repr=False)
    total_sugars: NutrientAmount | None = Field(default=None, alias="total_sugars", repr=False)
    added_sugars: NutrientAmount | None = Field(default=None, alias="added_sugars", repr=False)
    sodium: NutrientAmount | None = Field(default=None, alias="sodium", repr=False)

class CompleteScanNutritionFactsInput(TypedDict, total=False):
    calories: NutrientAmount | NutrientAmountInput
    protein: NutrientAmount | NutrientAmountInput
    carbohydrates: NutrientAmount | NutrientAmountInput
    net_carbohydrates: NutrientAmount | NutrientAmountInput
    total_fat: NutrientAmount | NutrientAmountInput
    saturated_fat: NutrientAmount | NutrientAmountInput
    fiber: NutrientAmount | NutrientAmountInput
    total_sugars: NutrientAmount | NutrientAmountInput
    added_sugars: NutrientAmount | NutrientAmountInput
    sodium: NutrientAmount | NutrientAmountInput

class ConsumedHistoricalFood(APIModel):
    "ConsumedHistoricalFood: typed API data. Unknown response fields are preserved."
    timestamp: datetime = Field(..., alias="timestamp", repr=False)
    id: FoodId = Field(..., alias="id", repr=False)
    serving: FoodLogInputServing = Field(..., alias="serving", repr=False)

class ConsumedHistoricalFoodInput(TypedDict, total=False):
    timestamp: Required[str | datetime]
    id: Required[FoodId]
    serving: Required[FoodLogInputServing | FoodLogInputServingInput]

class CorrectPhotoScanBody(APIModel):
    "CorrectPhotoScanBody: typed API data. Unknown response fields are preserved."
    meal_name: str | None = Field(default=None, alias="meal_name", repr=False, description="The meal name from the scan, when it returned one (photo scans do; text scans don't). Defaults to 'Meal'.")
    detections: list[FoodDetection] = Field(..., alias="detections", repr=False, description="The detections array from a photo or text food scan, exactly as returned. Omitted zero-value nutrient keys are filled in automatically; each detection needs at least one serving.")
    user_input: str = Field(..., alias="user_input", repr=False, description="Plain-English description of what to correct.")

class CorrectPhotoScanBodyInput(TypedDict, total=False):
    meal_name: str
    detections: Required[Sequence[FoodDetection | FoodDetectionInput]]
    user_input: Required[str]

class CreateClientTokenDto(APIModel):
    "CreateClientTokenDto: typed API data. Unknown response fields are preserved."
    end_user_id: str = Field(..., alias="end_user_id", repr=False, description="Your stable ID for the end user this token acts as. The token is bound to it; requests made with the token act only on this user.")
    scopes: list[str] | None = Field(default=None, alias="scopes", repr=False, description="What the token may do. Omit to grant the full client-grantable set (foods:read, food_scans:write, food_logs:read, food_logs:write, glucose:read, restaurants:read). Grant only what the screen needs.")
    ttl_seconds: float | None = Field(default=None, alias="ttl_seconds", repr=False, description="How long the token stays valid, in seconds. Between 300 and 7200; defaults to 1800.")

class CreateClientTokenDtoInput(TypedDict, total=False):
    end_user_id: Required[str]
    scopes: Sequence[Literal["foods:read", "food_scans:write", "food_logs:read", "food_logs:write", "glucose:read", "restaurants:read"]]
    ttl_seconds: float

class CreateFoodLogBody(APIModel):
    "CreateFoodLogBody: typed API data. Unknown response fields are preserved."
    foods: list[FoodLogInputFood] = Field(..., alias="foods", repr=False)
    timestamp_utc: datetime | None = Field(default=None, alias="timestamp_utc", repr=False, description="When the meal was eaten — any ISO-8601 offset; stored and returned in UTC. Omitted = now.")
    name: str | None = Field(default=None, alias="name", repr=False)

class CreateFoodLogBodyInput(TypedDict, total=False):
    foods: Required[Sequence[FoodLogInputFood | FoodLogInputFoodInput]]
    timestamp_utc: str | datetime
    name: str

class CreditsResponseDto(APIModel):
    "CreditsResponseDto: typed API data. Unknown response fields are preserved."
    plan: str = Field(..., alias="plan", repr=False, description="The plan this allowance comes from.")
    period_start: str = Field(..., alias="period_start", repr=False, description="First day of the current billing period (UTC), inclusive.")
    period_end: str = Field(..., alias="period_end", repr=False, description="Last day of the current billing period (UTC), inclusive.")
    resets_at: str = Field(..., alias="resets_at", repr=False, description="When the allowance resets and `used_credits` returns to 0.")
    included_credits: float | None = Field(default=None, alias="included_credits", repr=False, description="Credits included in the plan for this period. Absent when the plan has no ceiling.")
    used_credits: float = Field(..., alias="used_credits", repr=False, description="Credits used so far this period. One successful v1.2 API call costs 1 credit; failed calls cost nothing.")
    remaining_credits: float | None = Field(default=None, alias="remaining_credits", repr=False, description="Credits left in this period. Absent when the plan has no ceiling.")

    @property
    def resets_at_datetime(self) -> datetime | None:
        """Aware datetime when parseable; None for opaque/naive timestamps. Raw field is unchanged."""
        return parse_api_datetime(self.resets_at)

class CreditsResponseDtoInput(TypedDict, total=False):
    plan: Required[str]
    period_start: Required[str]
    period_end: Required[str]
    resets_at: Required[str]
    included_credits: float
    used_credits: Required[float]
    remaining_credits: float

class DeleteFoodLogResponse(APIModel):
    "DeleteFoodLogResponse: typed API data. Unknown response fields are preserved."
    status: str = Field(..., alias="status", repr=False, description="Deletion is idempotent — an unknown or already-deleted log_id returns the same response.")

class DeleteFoodLogResponseInput(TypedDict, total=False):
    status: Required[str]

class DetectedFood(APIModel):
    "DetectedFood: typed API data. Unknown response fields are preserved."
    id: FoodId | None = Field(default=None, alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(default=None, alias="brand_name", repr=False, description="Empty for generic (non-branded) foods.")
    nutrients: CompleteScanNutritionFacts = Field(..., alias="nutrients", repr=False)
    servings: list[DetectedServing] = Field(..., alias="servings", repr=False, description="Never empty: every detection producer guarantees at least one serving.")

class DetectedFoodInput(TypedDict, total=False):
    id: FoodId
    name: Required[str]
    brand_name: str
    nutrients: Required[CompleteScanNutritionFacts | CompleteScanNutritionFactsInput]
    servings: Required[Sequence[DetectedServing | DetectedServingInput]]

class DetectedServing(APIModel):
    "DetectedServing: typed API data. Unknown response fields are preserved."
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float | None = Field(default=None, alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)
    selected_quantity: float | None = Field(default=None, alias="selected_quantity", repr=False, description="Quantity the parser selected from the text ('2 cups' → 2); text scans only. Advisory — corrections reads the serving's own quantity.")

class DetectedServingInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: float
    unit: Required[str]
    selected_quantity: float

class ErrorResponse(APIModel):
    "ErrorResponse: typed API data. Unknown response fields are preserved."
    message: str = Field(..., alias="message", repr=False, description="A developer-facing explanation of what went wrong and how to fix it.")
    code: str = Field(..., alias="code", repr=False, description="A stable machine-readable identifier for the class of failure — build retry logic on this, never on message wording. Current values: invalid_request, unauthorized, forbidden, not_found, not_implemented, payload_too_large, rate_limited, internal_error, upstream_error, service_unavailable, upstream_timeout. Only rate_limited, internal_error, upstream_error, service_unavailable, and upstream_timeout are safe to retry (with backoff) — not_implemented is permanent until the feature ships. New codes may be added over time; treat an unknown code according to its HTTP status class.")
    docs_url: str = Field(..., alias="docs_url", repr=False, description="Link to the developer documentation for this API version.")

class ErrorResponseInput(TypedDict, total=False):
    message: Required[str]
    code: Required[str]
    docs_url: Required[str]

class FoodAlternative(APIModel):
    "FoodAlternative: typed API data. Unknown response fields are preserved."
    food: AlternativeFood = Field(..., alias="food", repr=False)

class FoodAlternativeInput(TypedDict, total=False):
    food: Required[AlternativeFood | AlternativeFoodInput]

class FoodDetection(APIModel):
    "FoodDetection: typed API data. Unknown response fields are preserved."
    confidence_score: ConfidenceScore | None = Field(default=None, alias="confidence_score", repr=False)
    food: DetectedFood = Field(..., alias="food", repr=False)

class FoodDetectionInput(TypedDict, total=False):
    confidence_score: ConfidenceScoreInput
    food: Required[DetectedFood | DetectedFoodInput]

class FoodLog(APIModel):
    "FoodLog: typed API data. Unknown response fields are preserved."
    id: FoodLogId = Field(..., alias="id", repr=False)
    foods: list[LoggedFood] = Field(..., alias="foods", repr=False)
    timestamp_utc: str = Field(..., alias="timestamp_utc", repr=False, description="Returned UTC timestamp. Treat as an opaque string because deployed responses are not consistently RFC 3339 formatted.")
    name: str | None = Field(default=None, alias="name", repr=False)

    @property
    def timestamp_utc_datetime(self) -> datetime | None:
        """Aware datetime when parseable; None for opaque/naive timestamps. Raw field is unchanged."""
        return parse_api_datetime(self.timestamp_utc)

class FoodLogInput(TypedDict, total=False):
    id: Required[FoodLogId]
    foods: Required[Sequence[LoggedFood | LoggedFoodInput]]
    timestamp_utc: Required[str | datetime]
    name: str | None

class FoodLogInputFood(APIModel):
    "FoodLogInputFood: typed API data. Unknown response fields are preserved."
    id: FoodId = Field(..., alias="id", repr=False)
    serving: FoodLogInputServing = Field(..., alias="serving", repr=False)

class FoodLogInputFoodInput(TypedDict, total=False):
    id: Required[FoodId]
    serving: Required[FoodLogInputServing | FoodLogInputServingInput]

class FoodLogInputServing(APIModel):
    "FoodLogInputServing: typed API data. Unknown response fields are preserved."
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float = Field(..., alias="quantity", repr=False, description="How many of that serving were consumed.")

class FoodLogInputServingInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: Required[float]

class FoodScan(APIModel):
    "FoodScan: typed API data. Unknown response fields are preserved."
    meal_name: str | None = Field(default=None, alias="meal_name", repr=False)
    total_nutrients: CompleteScanNutritionFacts | None = Field(default=None, alias="total_nutrients", repr=False, description="Aggregated nutrition across all detections.")
    detections: list[FoodDetection] = Field(..., alias="detections", repr=False, description="Detected foods. Always present — an empty array means nothing was recognized.")

class FoodScanInput(TypedDict, total=False):
    meal_name: str
    total_nutrients: CompleteScanNutritionFacts | CompleteScanNutritionFactsInput
    detections: Required[Sequence[FoodDetection | FoodDetectionInput]]

class FoodSearchItem(APIModel):
    "FoodSearchItem: typed API data. Unknown response fields are preserved."
    id: FoodId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(default=None, alias="brand_name", repr=False, description="Absent for generic (non-branded) foods.")
    nutrients: NutritionFacts = Field(..., alias="nutrients", repr=False, description="Per-serving nutrition in the shared nutrient vocabulary. Keys are omitted when the database has no value.")
    glycemic_index: float | None = Field(default=None, alias="glycemic_index", repr=False, description="Glycemic index.")
    glycemic_load: float | None = Field(default=None, alias="glycemic_load", repr=False, description="Glycemic load.")
    image_url: str | None = Field(default=None, alias="image_url", repr=False, description="URL of a picture of the food, when the database has one.")
    upc: str | None = Field(default=None, alias="upc", repr=False, description="The product's barcode, for branded foods that have one.")
    servings: list[ServingOption] = Field(..., alias="servings", repr=False)

class FoodSearchItemInput(TypedDict, total=False):
    id: Required[FoodId]
    name: Required[str]
    brand_name: str
    nutrients: Required[NutritionFacts | NutritionFactsInput]
    glycemic_index: float
    glycemic_load: float
    image_url: str
    upc: str
    servings: Required[Sequence[ServingOption | ServingOptionInput]]

class FoodSearchResults(APIModel):
    "FoodSearchResults: typed API data. Unknown response fields are preserved."
    total_count: float = Field(..., alias="total_count", repr=False, description="Total number of matches in the database; may exceed the number of items returned.")
    items: list[FoodSearchItem] = Field(..., alias="items", repr=False)

class FoodSearchResultsInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[Sequence[FoodSearchItem | FoodSearchItemInput]]

class FoodSuggestion(APIModel):
    "FoodSuggestion: typed API data. Unknown response fields are preserved."
    id: FoodId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False, description="Generic foods are lowercase; branded foods keep their product name.")
    brand_name: str | None = Field(default=None, alias="brand_name", repr=False, description="Absent for generic (non-branded) foods.")
    image_url: str | None = Field(default=None, alias="image_url", repr=False, description="Thumbnail of the food, when the database has one.")
    nutrients: NutritionFacts | None = Field(default=None, alias="nutrients", repr=False, description="Calories per default serving, in the shared nutrient vocabulary — the one nutrient a suggestion carries. Fetch the food for the full panel.")

class FoodSuggestionInput(TypedDict, total=False):
    id: Required[FoodId]
    name: Required[str]
    brand_name: str
    image_url: str
    nutrients: NutritionFacts | NutritionFactsInput

class GlucoseChart(APIModel):
    "GlucoseChart: typed API data. Unknown response fields are preserved."
    min: float = Field(..., alias="min", repr=False, description="Suggested Y-axis lower bound (mg/dL). A fixed target-range bound, not the minimum of the curve.")
    max: float = Field(..., alias="max", repr=False, description="Suggested Y-axis upper bound (mg/dL): 180 with Type 2 diabetes in health_conditions, otherwise 140. Not the maximum of the curve.")

class GlucoseChartInput(TypedDict, total=False):
    min: Required[float]
    max: Required[float]

class GlucosePrediction(APIModel):
    "GlucosePrediction: typed API data. Unknown response fields are preserved."
    prediction: list[GlucosePredictionPoint] = Field(..., alias="prediction", repr=False, description="The predicted glucose curve at 15-minute intervals, starting at start_time.")
    impact: GlucoseImpact = Field(..., alias="impact_score", repr=False)
    chart: GlucoseChart = Field(..., alias="chart", repr=False)

class GlucosePredictionInput(TypedDict, total=False):
    prediction: Required[Sequence[GlucosePredictionPoint | GlucosePredictionPointInput]]
    impact_score: Required[GlucoseImpactInput]
    chart: Required[GlucoseChart | GlucoseChartInput]

class GlucosePredictionPoint(APIModel):
    "GlucosePredictionPoint: typed API data. Unknown response fields are preserved."
    minutes: float = Field(..., alias="minutes", repr=False, description="Minutes after start_time.")
    value: float = Field(..., alias="value", repr=False, description="Predicted glucose, mg/dL.")

class GlucosePredictionPointInput(TypedDict, total=False):
    minutes: Required[float]
    value: Required[float]

class GlucosePredictionProfile(APIModel):
    "GlucosePredictionProfile: typed API data. Unknown response fields are preserved."
    age: float = Field(..., alias="age", repr=False)
    sex: Sex = Field(..., alias="sex", repr=False)
    height: Height = Field(..., alias="height", repr=False)
    weight: Weight = Field(..., alias="weight", repr=False)
    activity_level: ActivityLevel | None = Field(default=None, alias="activity_level", repr=False)
    health_conditions: list[MedicalCondition] | None = Field(default=None, alias="health_conditions", repr=False, description="Omit it (or send []) if none apply. Type 1 diabetes is not supported by the prediction model.")

class GlucosePredictionProfileInput(TypedDict, total=False):
    age: Required[float]
    sex: Required[SexInput]
    height: Required[Height | HeightInput]
    weight: Required[Weight | WeightInput]
    activity_level: ActivityLevelInput
    health_conditions: Sequence[MedicalConditionInput]

class Height(APIModel):
    "Height: typed API data. Unknown response fields are preserved."
    value: float = Field(..., alias="value", repr=False)
    unit: HeightUnit = Field(..., alias="unit", repr=False)

class HeightInput(TypedDict, total=False):
    value: Required[float]
    unit: Required[HeightUnitInput]

class ListFoodLogsResponse(APIModel):
    "ListFoodLogsResponse: typed API data. Unknown response fields are preserved."
    total_count: float = Field(..., alias="total_count", repr=False)
    items: list[FoodLog] = Field(..., alias="items", repr=False, description="Logs in the range, ordered by timestamp. An empty list is a valid result.")

class ListFoodLogsResponseInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[Sequence[FoodLog | FoodLogInput]]

class LoggedFood(APIModel):
    "LoggedFood: typed API data. Unknown response fields are preserved."
    id: FoodId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    brand_name: str | None = Field(default=None, alias="brand_name", repr=False)
    image_url: str | None = Field(default=None, alias="image_url", repr=False)
    glycemic_index: float | None = Field(default=None, alias="glycemic_index", repr=False)
    glycemic_load: float | None = Field(default=None, alias="glycemic_load", repr=False)
    nutrients: NutritionFacts = Field(..., alias="nutrients", repr=False, description="Scaled to the consumed serving.")
    consumed_serving: FoodLogInputServing = Field(..., alias="consumed_serving", repr=False, description="What was logged.")
    serving_details: ServingDetails = Field(..., alias="serving_details", repr=False, description="The serving definition the quantity refers to.")

class LoggedFoodInput(TypedDict, total=False):
    id: Required[FoodId]
    name: Required[str]
    brand_name: str | None
    image_url: str | None
    glycemic_index: float | None
    glycemic_load: float | None
    nutrients: Required[NutritionFacts | NutritionFactsInput]
    consumed_serving: Required[FoodLogInputServing | FoodLogInputServingInput]
    serving_details: Required[ServingDetails | ServingDetailsInput]

class NutrientAmount(APIModel):
    "NutrientAmount: typed API data. Unknown response fields are preserved."
    value: float = Field(..., alias="value", repr=False)
    unit: str = Field(..., alias="unit", repr=False)

class NutrientAmountInput(TypedDict, total=False):
    value: Required[float]
    unit: Required[str]

class NutritionFacts(APIModel):
    "NutritionFacts: typed API data. Unknown response fields are preserved."
    calories: NutrientAmount | None = Field(default=None, alias="calories", repr=False)
    protein: NutrientAmount | None = Field(default=None, alias="protein", repr=False)
    carbohydrates: NutrientAmount | None = Field(default=None, alias="carbohydrates", repr=False)
    net_carbohydrates: NutrientAmount | None = Field(default=None, alias="net_carbohydrates", repr=False)
    total_fat: NutrientAmount | None = Field(default=None, alias="total_fat", repr=False)
    trans_fat: NutrientAmount | None = Field(default=None, alias="trans_fat", repr=False)
    saturated_fat: NutrientAmount | None = Field(default=None, alias="saturated_fat", repr=False)
    fiber: NutrientAmount | None = Field(default=None, alias="fiber", repr=False)
    total_sugars: NutrientAmount | None = Field(default=None, alias="total_sugars", repr=False)
    added_sugars: NutrientAmount | None = Field(default=None, alias="added_sugars", repr=False)
    cholesterol: NutrientAmount | None = Field(default=None, alias="cholesterol", repr=False)
    calcium: NutrientAmount | None = Field(default=None, alias="calcium", repr=False)
    iron: NutrientAmount | None = Field(default=None, alias="iron", repr=False, description="Unit: mcg.")
    potassium: NutrientAmount | None = Field(default=None, alias="potassium", repr=False)
    sodium: NutrientAmount | None = Field(default=None, alias="sodium", repr=False)
    vitamin_d: NutrientAmount | None = Field(default=None, alias="vitamin_d", repr=False, description="Unit: IU.")

class NutritionFactsInput(TypedDict, total=False):
    calories: NutrientAmount | NutrientAmountInput
    protein: NutrientAmount | NutrientAmountInput
    carbohydrates: NutrientAmount | NutrientAmountInput
    net_carbohydrates: NutrientAmount | NutrientAmountInput
    total_fat: NutrientAmount | NutrientAmountInput
    trans_fat: NutrientAmount | NutrientAmountInput
    saturated_fat: NutrientAmount | NutrientAmountInput
    fiber: NutrientAmount | NutrientAmountInput
    total_sugars: NutrientAmount | NutrientAmountInput
    added_sugars: NutrientAmount | NutrientAmountInput
    cholesterol: NutrientAmount | NutrientAmountInput
    calcium: NutrientAmount | NutrientAmountInput
    iron: NutrientAmount | NutrientAmountInput
    potassium: NutrientAmount | NutrientAmountInput
    sodium: NutrientAmount | NutrientAmountInput
    vitamin_d: NutrientAmount | NutrientAmountInput

class PredictGlucoseBody(APIModel):
    "PredictGlucoseBody: typed API data. Unknown response fields are preserved."
    user_profile: GlucosePredictionProfile = Field(..., alias="user_profile", repr=False)
    foods: list[FoodLogInputFood] = Field(..., alias="foods", repr=False, description="The meal to predict the glucose response for.")
    start_time: datetime = Field(..., alias="start_time", repr=False, description="When the meal is (or will be) eaten. Must carry a timezone designator.")
    cgm_data: list[CgmReading] | None = Field(default=None, alias="cgm_data", repr=False, description="Optional CGM history for personalization; requires consumed_foods.")
    consumed_foods: list[ConsumedHistoricalFood] | None = Field(default=None, alias="consumed_foods", repr=False, description="The meals eaten during the CGM history; requires cgm_data.")

class PredictGlucoseBodyInput(TypedDict, total=False):
    user_profile: Required[GlucosePredictionProfile | GlucosePredictionProfileInput]
    foods: Required[Sequence[FoodLogInputFood | FoodLogInputFoodInput]]
    start_time: Required[str | datetime]
    cgm_data: Sequence[CgmReading | CgmReadingInput]
    consumed_foods: Sequence[ConsumedHistoricalFood | ConsumedHistoricalFoodInput]

class Restaurant(APIModel):
    "Restaurant: typed API data. Unknown response fields are preserved."
    type_: str = Field(..., alias="type", repr=False, description="When coordinates are provided and the name matches no restaurant, results may be menu items instead.")
    id: str = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    is_chain: bool | None = Field(default=None, alias="is_chain", repr=False)
    distance: float | None = Field(default=None, alias="distance", repr=False, description="Distance from (latitude, longitude) in meters; present only when coordinates were provided.")
    city: str | None = Field(default=None, alias="city", repr=False)
    address1: str | None = Field(default=None, alias="address1", repr=False)
    address2: str | None = Field(default=None, alias="address2", repr=False)

class RestaurantInput(TypedDict, total=False):
    type_: Required[Literal["restaurant", "menu_item"]]
    id: Required[str]
    name: Required[str]
    is_chain: bool
    distance: float
    city: str
    address1: str
    address2: str

class RestaurantMenuItem(APIModel):
    "RestaurantMenuItem: typed API data. Unknown response fields are preserved."
    type_: str = Field(..., alias="type", repr=False)
    id: RestaurantMenuItemId = Field(..., alias="id", repr=False)
    name: str = Field(..., alias="name", repr=False)
    restaurant_name: str = Field(..., alias="restaurant_name", repr=False)
    is_chain: bool | None = Field(default=None, alias="is_chain", repr=False)
    nutrients: NutritionFacts | None = Field(default=None, alias="nutrients", repr=False, description="Per-dish nutrition in the shared nutrient vocabulary. Keys are omitted when the menu source has no value.")
    glycemic_index: float | None = Field(default=None, alias="glycemic_index", repr=False, description="Glycemic index.")
    glycemic_load: float | None = Field(default=None, alias="glycemic_load", repr=False, description="Glycemic load.")
    image_url: str | None = Field(default=None, alias="image_url", repr=False, description="URL of a picture of the dish, when the source has one.")
    distance: float | None = Field(default=None, alias="distance", repr=False, description="Distance from (latitude, longitude) in meters.")
    servings: list[ServingOption] = Field(..., alias="servings", repr=False)

class RestaurantMenuItemInput(TypedDict, total=False):
    type_: Required[str]
    id: Required[RestaurantMenuItemId]
    name: Required[str]
    restaurant_name: Required[str]
    is_chain: bool
    nutrients: NutritionFacts | NutritionFactsInput
    glycemic_index: float
    glycemic_load: float
    image_url: str
    distance: float
    servings: Required[Sequence[ServingOption | ServingOptionInput]]

class ScanFoodPhotoBody(APIModel):
    "ScanFoodPhotoBody: typed API data. Unknown response fields are preserved."
    image: str = Field(..., alias="image", repr=False, description="The meal photo, as an http(s) URL or a base64 data URI (data:image/jpeg;base64,…). Any image of the meal works — a camera photo, a screenshot, or a hosted picture. Formats: JPG, PNG, WEBP, and non-animated GIF. A URL must be publicly fetchable server-side: hosts that block hotlinking or require a login cannot be read. Prefer the URL when the image is already hosted — base64 inflates the payload by ~33%, and request bodies over 5 MB are rejected, so keep raw images under ~3.5 MB when encoding.")

class ScanFoodPhotoBodyInput(TypedDict, total=False):
    image: Required[str]

class SearchFoodsByNaturalLanguageBody(APIModel):
    "SearchFoodsByNaturalLanguageBody: typed API data. Unknown response fields are preserved."
    text: str = Field(..., alias="text", repr=False, description="Natural-language description of what was eaten; parsed into detected foods with quantities.")

class SearchFoodsByNaturalLanguageBodyInput(TypedDict, total=False):
    text: Required[str]

class SearchRestaurantMenuItemsResponse(APIModel):
    "SearchRestaurantMenuItemsResponse: typed API data. Unknown response fields are preserved."
    total_count: float = Field(..., alias="total_count", repr=False, description="Total number of matches; may exceed the number of items returned.")
    items: list[RestaurantMenuItem] = Field(..., alias="items", repr=False)

class SearchRestaurantMenuItemsResponseInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[Sequence[RestaurantMenuItem | RestaurantMenuItemInput]]

class SearchRestaurantsResponse(APIModel):
    "SearchRestaurantsResponse: typed API data. Unknown response fields are preserved."
    total_count: float = Field(..., alias="total_count", repr=False, description="Total number of matches; may exceed the number of items returned.")
    items: list[Restaurant] = Field(..., alias="items", repr=False)

class SearchRestaurantsResponseInput(TypedDict, total=False):
    total_count: Required[float]
    items: Required[Sequence[Restaurant | RestaurantInput]]

class ServingDetails(APIModel):
    "ServingDetails: typed API data. Unknown response fields are preserved."
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float = Field(..., alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)
    weight_grams: float | None = Field(default=None, alias="weight_grams", repr=False)

class ServingDetailsInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: Required[float]
    unit: Required[str]
    weight_grams: float | None

class ServingOption(APIModel):
    "ServingOption: typed API data. Unknown response fields are preserved."
    id: ServingId = Field(..., alias="id", repr=False)
    quantity: float = Field(..., alias="quantity", repr=False)
    unit: str = Field(..., alias="unit", repr=False)
    scaling_factor: float = Field(..., alias="scaling_factor", repr=False, description="Multiplier applied to the food's nutrition values for this serving.")
    weight_grams: float | None = Field(..., alias="weight_grams", repr=False)
    is_primary: bool = Field(..., alias="is_primary", repr=False, description="Whether this is the default serving for the food.")

class ServingOptionInput(TypedDict, total=False):
    id: Required[ServingId]
    quantity: Required[float]
    unit: Required[str]
    scaling_factor: Required[float]
    weight_grams: Required[float | None]
    is_primary: Required[bool]

class SuggestFoodAlternativesBody(APIModel):
    "SuggestFoodAlternativesBody: typed API data. Unknown response fields are preserved."
    diet_restrictions: list[DietRestriction] | None = Field(default=None, alias="diet_restrictions", repr=False, description="Allergens/ingredients to avoid. Omit it (or send []) if none apply.")
    diet_preferences: list[DietPreference] | None = Field(default=None, alias="diet_preferences", repr=False, description="Dietary patterns to match. Omit it (or send []) if none apply.")

class SuggestFoodAlternativesBodyInput(TypedDict, total=False):
    diet_restrictions: Sequence[DietRestrictionInput]
    diet_preferences: Sequence[DietPreferenceInput]

class SuggestFoodAlternativesResponse(APIModel):
    "SuggestFoodAlternativesResponse: typed API data. Unknown response fields are preserved."
    alternatives: list[FoodAlternative] = Field(..., alias="alternatives", repr=False, description="Healthier alternatives matching the restrictions and preferences. An empty array is a valid result, not an error.")

class SuggestFoodAlternativesResponseInput(TypedDict, total=False):
    alternatives: Required[Sequence[FoodAlternative | FoodAlternativeInput]]

class UpdateFoodLogBody(APIModel):
    "UpdateFoodLogBody: typed API data. Unknown response fields are preserved."
    foods: list[FoodLogInputFood] | None = Field(default=None, alias="foods", repr=False)
    timestamp_utc: str | None = Field(default=None, alias="timestamp_utc", repr=False, description="UTC consumption time, ending in Z.")
    name: str | None = Field(default=None, alias="name", repr=False)

    @property
    def timestamp_utc_datetime(self) -> datetime | None:
        """Aware datetime when parseable; None for opaque/naive timestamps. Raw field is unchanged."""
        return parse_api_datetime(self.timestamp_utc) if self.timestamp_utc is not None else None

class UpdateFoodLogBodyInput(TypedDict, total=False):
    foods: Sequence[FoodLogInputFood | FoodLogInputFoodInput]
    timestamp_utc: str | datetime
    name: str

class Weight(APIModel):
    "Weight: typed API data. Unknown response fields are preserved."
    value: float = Field(..., alias="value", repr=False)
    unit: WeightUnit = Field(..., alias="unit", repr=False)

class WeightInput(TypedDict, total=False):
    value: Required[float]
    unit: Required[WeightUnitInput]

# Resolve forward references after every schema has been declared.
AlternativeFood.model_rebuild()
AlternativeServing.model_rebuild()
ApiErrorDto.model_rebuild()
AutocompleteFoodsResponse.model_rebuild()
CgmReading.model_rebuild()
ClientTokenResponseDto.model_rebuild()
CompleteScanNutritionFacts.model_rebuild()
ConsumedHistoricalFood.model_rebuild()
CorrectPhotoScanBody.model_rebuild()
CreateClientTokenDto.model_rebuild()
CreateFoodLogBody.model_rebuild()
CreditsResponseDto.model_rebuild()
DeleteFoodLogResponse.model_rebuild()
DetectedFood.model_rebuild()
DetectedServing.model_rebuild()
ErrorResponse.model_rebuild()
FoodAlternative.model_rebuild()
FoodDetection.model_rebuild()
FoodLog.model_rebuild()
FoodLogInputFood.model_rebuild()
FoodLogInputServing.model_rebuild()
FoodScan.model_rebuild()
FoodSearchItem.model_rebuild()
FoodSearchResults.model_rebuild()
FoodSuggestion.model_rebuild()
GlucoseChart.model_rebuild()
GlucosePrediction.model_rebuild()
GlucosePredictionPoint.model_rebuild()
GlucosePredictionProfile.model_rebuild()
Height.model_rebuild()
ListFoodLogsResponse.model_rebuild()
LoggedFood.model_rebuild()
NutrientAmount.model_rebuild()
NutritionFacts.model_rebuild()
PredictGlucoseBody.model_rebuild()
Restaurant.model_rebuild()
RestaurantMenuItem.model_rebuild()
ScanFoodPhotoBody.model_rebuild()
SearchFoodsByNaturalLanguageBody.model_rebuild()
SearchRestaurantMenuItemsResponse.model_rebuild()
SearchRestaurantsResponse.model_rebuild()
ServingDetails.model_rebuild()
ServingOption.model_rebuild()
SuggestFoodAlternativesBody.model_rebuild()
SuggestFoodAlternativesResponse.model_rebuild()
UpdateFoodLogBody.model_rebuild()
Weight.model_rebuild()
